export let passions = [
  "3D printing",
  "Acroyoga",
  "Acting",
  "Aerial silk",
  "Airbrushing",
  "Amateur radio",
  "Animation",
  "Aquascaping",
  "Art",
  "Astrology",
  "Babysitting",
  "Baking",
  "Basketball",
  "Baton twirling",
  "Beatboxing",
  "Beer tasting",
  "Binge-watching",
  "Blogging",
  "Board/tabletop games",
  "Book discussion clubs",
  "Book restoration",
  "Bowling",
  "Brazilian jiu-jitsu",
  "Breadmaking",
  "Building",
  "Bullet journaling",
  "Calligraphy",
  "Candle making",
  "Candy making",
  "Car fixing & building",
  "Card games",
  "Cardistry",
  "Ceramics",
  "Chatting",
  "Cheesemaking",
  "Chess",
  "Cleaning",
  "Clothesmaking",
  "Coffee roasting",
  "Collecting",
  "Coloring",
  "Communication",
  "Community activism",
  "Computer programming",
  "Confectionery",
  "Construction",
  "Cooking",
  "Cosplaying",
  "Couch surfing",
  "Couponing",
  "Craft",
  "Creative writing",
  "Crocheting",
  "Cross-stitch",
  "Crossword puzzles",
  "Cryptography",
  "Cue sports",
  "Dance",
  "Decorating",
  "Digital arts",
  "Dining",
  "Diorama",
  "Distro Hopping",
  "Diving",
  "Djembe",
  "DJing",
  "Do it yourself",
  "Drama",
  "Drawing",
  "Drink mixing",
  "Drinking",
  "Electronic games",
  "Electronics",
  "Embroidery",
  "Engraving",
  "Entertaining",
  "Experimenting",
  "Fantasy sports",
  "Fashion",
  "Fashion design",
  "Feng shui decorating",
  "Filmmaking",
  "Fingerpainting",
  "Fishfarming",
  "Fishkeeping",
  "Flower arranging",
  "Fly tying",
  "Foreign language learning",
  "Furniture building",
  "Tabletop games", 
  "Role-playing games", 
  "Electronic games",
  "Genealogy",
  "Gingerbread house making",
  "Giving advice",
  "Glassblowing",
  "Graphic design",
  "Gunsmithing",
  "Gymnastics",
  "Hacking",
  "Hardware",
  "Herp keeping",
  "Home improvement",
  "Homebrewing",
  "Houseplant care",
  "Hula hooping",
  "Humor",
  "Hydroponics",
  "Ice skating",
  "Inventing",
  "Jewelry making",
  "Jigsaw puzzles",
  "Journaling",
  "Juggling",
  "Karaoke",
  "Karate",
  "Kendama",
  "Knife making",
  "Knitting",
  "Knot tying",
  "Kombucha brewing",
  "Kung fu",
  "Lace making",
  "Lapidary",
  "Leather crafting",
  "Lego building",
  "Livestreaming",
  "Listening to music",
  "Listening to podcasts",
  "Lock picking",
  "Machining",
  "Macrame",
  "Magic",
  "Makeup",
  "Massaging",
  "Mazes",
  "Mechanics",
  "Meditation",
  "Memory training",
  "Metalworking",
  "Miniature art",
  "Minimalism",
  "Model building",
  "Model engineering",
  "Music",
  "Nail art",
  "Needlepoint",
  "Origami",
  "Painting",
  "Palmistry",
  "Performance",
  "Pet",
  "Pet adoption & fostering",
  "Pet sitting",
  "Philately",
  "Photography",
  "Pilates",
  "Planning",
  "Plastic art",
  "Playing musical instruments",
  "Poetry",
  "Poi",
  "Pole dancing",
  "Postcrossing",
  "Pottery",
  "Powerlifting",
  "Practical jokes",
  "Pressed flower craft",
  "Proofreading and editing",
  "Proverbs",
  "Public speaking",
  "Puppetry",
  "Puzzles",
  "Pyrography",
  "Quilling",
  "Quilting",
  "Quizzes",
  "Radio-controlled model playing",
  "Rail transport modeling",
  "Rapping",
  "Reading",
  "Recipe creation",
  "Refinishing",
  "Reiki",
  "Reviewing Gadgets",
  "Robot combat",
  "Rubik's Cube",
  "Scrapbooking",
  "SCUBA Diving",
  "Sculpting",
  "Sewing",
  "Shoemaking",
  "Singing",
  "Sketching",
  "Skipping rope",
  "Slot car",
  "Soapmaking",
  "Social media",
  "Spreadsheets",
  "Stamp collecting",
  "Stand-up comedy",
  "Storytelling",
  "Stripping",
  "Sudoku",
  "Table tennis playing",
  "Tapestry",
  "Tarot",
  "Tatebanko",
  "Tattooing",
  "Taxidermy",
  "Telling jokes",
  "Thrifting",
  "Upcycling",
  "Video editing",
  "Video game developing",
  "Video gaming",
  "Video making",
  "VR Gaming",
  "Wargaming",
  "Watching documentaries",
  "Watching movies",
  "Watching television",
  "Waxing",
  "Weaving",
  "Webtooning",
  "Weight training",
  "Welding",
  "Whittling",
  "Wii sports",
  "Wikipedia editing",
  "Wine tasting",
  "Winemaking",
  "Witchcraft",
  "Wood carving",
  "Woodworking",
  "Word searches",
  "Worldbuilding",
  "Writing",
  "Writing music",
  "Yo-yoing",
  "Yoga",
  "Zumba",
  "Air sports",
  "Airsoft",
  "Amateur geology",
  "Amusement park visiting",
  "Archery",
  "Auto detailing",
  "Automobilism",
  "Astronomy",
  "Backpacking",
  "Badminton",
  "BASE jumping",
  "Baseball",
  "Basketball",
  "Beachcombing",
  "Beekeeping",
  "Birdwatching",
  "Blacksmithing",
  "BMX",
  "Board sports",
  "Bodybuilding",
  "Bonsai",
  "Butterfly watching",
  "Bus riding",
  "Camping",
  "Canoeing",
  "Canyoning",
  "Car riding",
  "Car tuning",
  "Caving",
  "City trip",
  "Composting",
  "Cycling",
  "Dandyism",
  "Dog training",
  "Dog walking",
  "Dowsing",
  "Driving",
  "Farming",
  "Fishing",
  "Flag football",
  "Flower growing",
  "Flying",
  "Flying disc",
  "Flying model planes",
  "Foraging",
  "Fossicking",
  "Freestyle football",
  "Fruit picking",
  "Gardening",
  "Geocaching",
  "Ghost hunting",
  "Gold prospecting",
  "Graffiti",
  "Groundhopping",
  "Guerrilla gardening",
  "Handball",
  "Herbalism",
  "Herping",
  "High-power rocketry",
  "Hiking",
  "Hobby horsing",
  "Hobby tunneling",
  "Hooping",
  "Horseback riding",
  "Hunting",
  "Inline skating",
  "Jogging",
  "Jumping rope",
  "Karting",
  "Kayaking",
  "Kite flying",
  "Kitesurfing",
  "Lacrosse",
  "LARPing",
  "Letterboxing",
  "Lomography",
  "Longboarding",
  "Martial arts",
  "Metal detecting",
  "Motorcycling",
  "Meteorology",
  "Motor sports",
  "Mountain biking",
  "Mountaineering",
  "Museum visiting",
  "Mushroom hunting/mycology",
  "Netball",
  "Noodling",
  "Nordic skating",
  "Orienteering",
  "Paintball",
  "Paragliding",
  "Parkour",
  "Photography",
  "Picnicking",
  "Podcast hosting",
  "Polo",
  "Public transport riding",
  "Qigong",
  "Radio-controlled model playing",
  "Rafting",
  "Railway journeys",
  "Rappelling",
  "Renaissance fair",
  "Renovating",
  "Road biking",
  "Rock climbing",
  "Rock painting",
  "Roller skating",
  "Rugby",
  "Running",
  "Sailing",
  "Sand art",
  "Scouting",
  "Scuba diving",
  "Sculling or rowing",
  "Shooting",
  "Shopping",
  "Shuffleboard",
  "Skateboarding",
  "Skiing",
  "Skimboarding",
  "Skydiving",
  "Slacklining",
  "Sledding",
  "Snorkeling",
  "Snowboarding",
  "Snowmobiling",
  "Snowshoeing",
  "Soccer",
  "Stone skipping",
  "Storm chasing",
  "Sun bathing",
  "Surfing",
  "Survivalism",
  "Swimming",
  "Taekwondo",
  "Tai chi",
  "Tennis",
  "Thru-hiking",
  "Topiary",
  "Tourism",
  "Trade fair visiting",
  "Travel",
  "Urban exploration",
  "Vacation",
  "Vegetable farming",
  "Vehicle restoration",
  "Videography",
  "Volunteering",
  "Walking",
  "Water sports",
  "Zoo visiting",
  "Archaeology",
  "Astronomy",
  "Biology",
  "Chemistry",
  "Electrochemistry",
  "English",
  "Geography",
  "History",
  "Mathematics",
  "Medical science",
  "Microbiology",
  "Philosophy",
  "Physics",
  "Psychology",
  "Railway studies",
  "Research",
  "Science and technology studies",
  "Social studies",
  "Sports science",
  "Life Science",
  "Teaching",
  "Web design",
  "Antiquing",
  "Ant-keeping",
  "Art collecting",
  "Book collecting",
  "Button collecting",
  "Cartophily (card collecting)",
  "Coin collecting",
  "Comic book collecting",
  "Compact discs",
  "Deltiology (postcard collecting)",
  "Digital hoarding",
  "Dolls",
  "Element collecting",
  "Ephemera collecting",
  "Films",
  "Fingerprint collecting",
  "Fusilately (phonecard collecting)",
  "Knife collecting",
  "Lotology (lottery ticket collecting)",
  "Movie memorabilia collecting",
  "Perfume",
  "Philately",
  "Phillumeny",
  "Radio-controlled model collecting",
  "Rail transport modelling",
  "Record collecting",
  "Rock tumbling",
  "Scutelliphily",
  "Shoes",
  "Sports memorabilia",
  "Stamp collecting",
  "Stuffed toy collecting",
  "Tea bag collecting",
  "Ticket collecting",
  "Tambi",
  "Transit map collecting",
  "Video game collecting",
  "Vintage cars",
  "Vintage clothing",
  "Vinyl Records",
  "Antiquities",
  "Auto audiophilia",
  "Flower collecting and pressing",
  "Fossil hunting",
  "Insect collecting",
  "Leaves",
  "Magnet fishing",
  "Metal detecting",
  "Mineral collecting",
  "Rock balancing",
  "Sea glass collecting",
  "Seashell collecting",
  "Stone collecting",
  "Animal fancy",
  "Axe throwing",
  "Backgammon",
  "Badminton",
  "Baton twirling",
  "Beauty pageants",
  "Billiards",
  "Bowling",
  "Boxing",
  "Bridge",
  "Checkers (draughts)",
  "Cheerleading",
  "Chess",
  "Color guard",
  "Cribbage",
  "Curling",
  "Dancing",
  "Darts",
  "Debate",
  "Dominoes",
  "Eating",
  "Esports",
  "Fencing",
  "Go",
  "Gymnastics",
  "Ice hockey",
  "Ice skating",
  "Judo",
  "Jujitsu",
  "Kabaddi",
  "Knowledge/word games",
  "Laser tag",
  "Longboarding",
  "Magic",
  "Mahjong",
  "Marbles",
  "Martial arts",
  "Model racing",
  "Model United Nations",
  "Poker",
  "Pole dancing",
  "Pool",
  "Radio-controlled model playing",
  "Role-playing games",
  "Shogi",
  "Slot car racing",
  "Speedcubing",
  "Sport stacking",
  "Table football",
  "Table tennis",
  "Volleyball",
  "Video gaming",
  "VR Gaming",
  "Weightlifting",
  "Wrestling",
  "Airsoft",
  "Archery",
  "Association football",
  "Australian rules football",
  "Auto racing",
  "Baseball",
  "Beach volleyball",
  "Breakdancing",
  "Climbing",
  "Cornhole",
  "Cricket",
  "Croquet",
  "Cycling",
  "Disc golf",
  "Dog sport",
  "Equestrianism",
  "Exhibition drill",
  "Field hockey",
  "Figure skating",
  "Fishing",
  "Fitness",
  "Footbag",
  "Frisbee",
  "Golfing",
  "Handball",
  "Horseback riding",
  "Horsemanship",
  "Horseshoes",
  "Iceboat racing",
  "Jukskei",
  "Kart racing",
  "Knife throwing",
  "Lacrosse",
  "Longboarding",
  "Long-distance running",
  "Marching band",
  "Mini Golf",
  "Model aircraft",
  "Orienteering",
  "Pickleball",
  "Powerboat racing",
  "Quidditch",
  "Race walking",
  "Racquetball",
  "Radio-controlled car racing",
  "Radio-controlled model playing",
  "Roller derby",
  "Rugby league football",
  "Sculling or rowing",
  "Shooting sport",
  "Skateboarding",
  "Skiing",
  "Sled dog racing",
  "Softball",
  "Speed skating",
  "Squash",
  "Surfing",
  "Swimming",
  "Table tennis",
  "Tennis",
  "Tennis polo",
  "Tether car",
  "Tour skating",
  "Tourism",
  "Trapshooting",
  "Triathlon",
  "Ultimate frisbee",
  "Volleyball",
  "Water polo",
  "Audiophile",
  "Fishkeeping",
  "Learning",
  "Meditation",
  "Microscopy",
  "Reading",
  "Research",
  "Shortwave listening",
  "Aircraft spotting",
  "Amateur astronomy",
  "Benchmarking",
  "Birdwatching",
  "Bus spotting",
  "Geocaching",
  "Gongoozling",
  "Herping",
  "Hiking/backpacking",
  "Meteorology",
  "People-watching",
  "Photography",
  "Satellite watching",
  "Trainspotting",
  "Whale watching",
  ]
